/*
  nvm use 8.16.0
  node index.js
*/
const EventEmitter = require('events').EventEmitter
const { RandStream, asyncOp } = require('./lib/lib')

/*
  Problem #1 
  Create a function doAsync which accepts an array arr as input. Each element in the array can be either of type String or [String].
*/

const input = ['A', ['B', 'C'], 'D']

function* init(arr) {
  for (let item of arr) {
    yield item
  }
}

// Wrap the asyncOp in a Promise (by passing the resolve as the callback parameter)
const promisifyAsyncOp = (item) => {
  return new Promise((resolve) => {
    asyncOp(item, () => {
      resolve()
    })
  })
}

const doAsync = (arr) => {
  const iterable = init(arr)

  // recursion: run until iterable is done
  const runAsync = async () => {
    let { value, done } = iterable.next()
    if (done) {
      return
    }

    if (Array.isArray(value)) {
      // Use Promise.all to apply asyncOp to the items simultaneously
      let promises = value.map(async (v) => await promisifyAsyncOp(v))
      await Promise.all(promises)
    } else {
      await promisifyAsyncOp(value)
    }

    runAsync()
  }

  runAsync()
}

// ** note i did not do any more validation of the input (String or [String]).
doAsync(input)



/*
  Problem #2
  Create a class RandStringSource which accepts an instance of the class RandStream as input. RandStringSource should be a subclass of events.EventEmitter.

  Given the stream of random characters generated by RandStream, RandStringSource should emit an event data whenever a string enclosed by . is detected. The enclosed string should be used as payload in the data event.
*/

class RandStringSource extends EventEmitter {
  constructor(randStreamInstance) {
    super(randStreamInstance)

    // default string
    let str = ''
    randStreamInstance.on('data', (data) => {
      // add every word from the readStream to the default string
      str += data

      // split to get all strings between the dotsf
      let encapsulatedWords = str.split('.')

      if (!str.endsWith('.')) {
        // if string does not end with a dot, make default string the last item in the array returned by the encapsulatedWords.pop()
        str = encapsulatedWords.pop()
      }

      encapsulatedWords.forEach((word) => {
        if (word) {
          // Emit word if not empty
          this.emit('data', word)
        }
      })
    })
  }
}

let source = new RandStringSource(new RandStream())

source.on('data', (data) => {
  console.log('SOURCE: ', data)
})
